### ISSUE TITLE
De0-nano status

### ISSUE THREAD

**Issue by mczerski** [minimig-dev/MinimigAGA-MiST-TC64#11]
What is the status of de0-nano support in this project ?
I updated pinout to suite my extension board with VGA, sd card and PS2 keyboard and loaded the project to de0-nano but i only get a green screen on the tv (TV correctly detect signal).
In compilation report there are a lot of timing constraint violations on114MHz clock...

**Comment by robinsonb5** [comment]
The de0-nano port hasn't been tested, since none of the current devs has a suitable board.

Having said that, if you're seeing a green screen then the boot process is at least beginning and the SD card has been successfully initialised, and the SDRAM is working well enough for the CPU to execute a little bit of diagnostic code.

On boot the firmware uploads a tiny routine to Kickstart ROM space which repeatedly writes to the background colour register at $dff180.  The boot firmware then patches that routine on the fly to change the screen's colour.

Initially it's white.
Red means the SD card failed to initialise
Yellow means the boot firmware couldn't find a filesystem on the SD card
Green means the filesystem was mounted successfully, but the boot firmware couldn't find the controller firmware file, 832OSDAD.BIN, which must be on the SD card alongside the kick.rom file.

If all goes to plan, the OSD firmware will be loaded and control handed over to it, at which point the screen should go black, the Minimig logo will appear (if the artwork files are on the SD card) and some text will announce the loading of the Kickstart ROM.

I've attached that OSD firmwar file, in case you don't want to install the 832 toolchain and compile it yourself.
[832OSDAD.bin.zip](https://github.com/minimig-dev/MinimigAGA-MiST-TC64/files/13928315/832OSDAD.bin.zip)

**Comment by mczerski** [comment]
Thank You very much !!! :)

So after adding osd firmware to SD card I can see change in behaviour -
that is good. But .... screen goes black and stays that way. I can see that
my TV is loosing signal, this may be caused by the PAL mode which my TV is
not able to receive. Reading firmware code it seems I can force 31khz NTSC
mode by pressing F3 on keyboard during boot, but this does not work either
(actually I tried all F1 to F6 keys).

sob., 13 sty 2024 o 15:33 Alastair M. Robinson ***@***.***>
napisał(a):

**Comment by mczerski** [comment]
Yeah, so I hardcoded 31khz NTSC info the fpga and I'm able to launch workbench !!! Keyboard in osd works so keyboard is ok for sure. So how to set 31khz NTSC without hardcoding it into the fpga ?

**Comment by robinsonb5** [comment]
Once you're able to see and operate the OSD, you should be able to save a configuration file, which should store the state of both the PAL/NTSC setting and the scandoubler switch.

Glad to hear you were able to get it running - that's great news!

**Comment by mczerski** [comment]
ok, thank You for your help. I'm closing this issue since everything seems to be working.
